PulseParams pulse_params
string mesh_filepath # Filepath to the mesh representing the surface to be painted (may change to the actual mesh object later, but for now will use filepath)
geometry_msgs/PoseArray[] poses # Array of poses representing the positions and orientations of the spray nozzle

---

Texture texture # Resulting paint thickness map 
string message  # Status message
bool success   # Indicates if the pulse operation was successful